name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: mageia:9

    steps:
    - name: Install packages
      run: dnf install -y git gcc make nim libclamav-static-devel libyara-devel
    - name: Get RkCheck
      run: |
        git clone https://github.com/dmknght/rkcheck
        cd rkcheck
    - name: build
      run: make build
