name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: centos:7

    steps:
    - name: Install packages
      run: yum install -y git gcc make nim libclamav-static-devel libyara-devel
    - name: build
      run: make build
