name: Debian SID

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:sid

    steps:
    - name: Check Update
      run: apt update
    - name: Install packages
      run: apt install -y git gcc-13 make nim libclamav-dev libyara-dev
    - name: Get RkCheck
      run: git clone https://github.com/dmknght/rkcheck
    - name: build
      run: make build
      working-directory: rkcheck
