name: Debian SID

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:sid
    steps:
    - name: Install packages
      run: |
        apt update
        apt install -y git gcc make nim libclamav-dev libyara-dev liblzma-dev libzstd-dev
    - name: Get RkCheck
      run: git clone https://github.com/dmknght/rkcheck
    - name: build
      run: make build
      working-directory: rkcheck